//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isrpo18
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class employees
    {
        [JsonPropertyName("CodeStaff")]
        public string id_e { get; set; }

        [JsonPropertyName("Position")]
        public string role_e { get; set; }

        [JsonPropertyName("FullName")]
        public string fio_e { get; set; }

        [JsonPropertyName("Log")]
        public string login_e { get; set; }

        [JsonPropertyName("Password")]
        public string password_e { get; set; }

        [JsonPropertyName("LastEnter")]
        public string last_e { get; set; }

        [JsonPropertyName("TypeEnter")]
        public string type_e { get; set; }
    }
}
